package:
    name: shimadzu_pump
    version: 1.4.3

build:
    noarch: python
    number: 0
    entry_points:
      - shimadzu_pump_ioc = shimadzu_pump.run:main

source:
    path: ..

requirements:
    build:
        - python >=3.8
    run:
        - python >=3.8
        - requests
        - pcaspy

about:
    summary: "Just a Shimadzu pump controller. Docs at https://github.com/paulscherrerinstitute/shimadzu_pump"
